### ISSUE TITLE
What exactly is the experimental part about this plugin?

### ISSUE THREAD

**Issue by philippthiele** [cloudfoundry/cpu-entitlement-plugin#93]
Is it not guaranteed to work always?
Can it impact the app in some way?
Are the recommendations it gives experimental?

Mainly I want to know: Could we use this plugin to regularly get the data from CF to push the data into our monitoring to automatically get notified when we are running over our entitled CPU share?

**Comment by ameowlia** [comment]
Hi @philippthiele,

This plugin (not the underlying feature itself) is experimental because we always hoped to get it merged into the main CLI. There are no known issues that I know of with this plugin, but as you can see, it doesn't get a lot of attention.

**Comment by ameowlia** [comment]
This exact CLI plugin is probably never going to be merged into the CF CLI, but others are currently working on exposing very similar functionality in a GA way.

[Here is a PR that adds the cpu_entitlement value to the /stats cloud controller endpoint. ](https://github.com/cloudfoundry/cloud_controller_ng/pull/3641)
